<?php include_once('header.php');?>
    <!-- Start Hero Area -->
    <section id="home" class="hero-area">
        <div class="container">
            <div class="row align-items-center" style="display:none;">
                <div class="col-lg-5 col-md-12 col-12">
                    <div class="hero-content">
                        <h1 class="wow fadeInLeft" data-wow-delay=".4s">A powerful app for your business.</h1>
                        <p class="wow fadeInLeft" data-wow-delay=".6s">From open source to pro services, Piqes helps you
                            to build, deploy, test, and monitor apps.</p>
                        <div class="button wow fadeInLeft" data-wow-delay=".8s">
                            <a href="javascript:void(0)" class="btn"><i class="lni lni-apple"></i> App Store</a>
                            <a href="javascript:void(0)" class="btn btn-alt"><i class="lni lni-play-store"></i> Google
                                Play</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-7 col-md-12 col-12">
                    <div class="hero-image wow fadeInRight" data-wow-delay=".4s">
                        <img src="assets/images/hero/phone.png" alt="#">
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End Hero Area -->

    <!-- Start Features Area -->
    <section id="features" class="features section" style="color: #000000;">
        <div class="container">
            <div class="row">
        
            </div>
            <div class="row">

                <div class="col-lg-12 col-md-6 col-12" style="margin-top:5%;">
          <p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:center;'>TERMS OF SERVICE</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:center;'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>OVERVIEW</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>This website is operated by <strong>Fashion Trades & Agencies Private Limited</strong>. Throughout the site, the terms &ldquo;we&rdquo;, &ldquo;us&rdquo; and &ldquo;our&rdquo; refer to<strong>&nbsp;</strong><strong>FTAPL</strong>.&nbsp;Fashion Trades & Agencies Private Limited&nbsp;offers this website, including all information, tools and services available from this site to you, the user, conditioned upon your acceptance of all terms, conditions, policies and notices stated here.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>By visiting our site and/ or paying the outstanding EMI taken from us, you engage in our &ldquo;Service&rdquo; and agree to be bound by the following terms and conditions (&ldquo;Terms of Service&rdquo;, &ldquo;Terms&rdquo;), including those additional terms and conditions and policies referenced herein and/or available by hyperlink.&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>As a user (&quot;User&quot; or &quot;You&quot;) of the Platform, you understand that Fashion Trades & Agencies Private Limited is a RBI registered NBFC which is currently only responsible for collecting the outstanding EMI from the customer , an individual, resident of India (also referred to as &quot;Borrower&quot; which expression shall, unless repugnant to the context or meaning thereof include its successors and assigns) .Currently Fashion Trades & Agencies Private Limited is no longer our service provider.&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>Please read these Terms &amp; Conditions carefully before accessing or using our Platform or any part thereof. By accessing or using any part of the Platform, You agree to be bound by these Terms &amp; Conditions. If You do not agree to all the terms and conditions, then <strong>YOU MAY NOT ACCESS THE PLATFORM OR USE ANY SERVICES PROVIDED BY US</strong>.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>These Terms and Conditions form a legal and binding agreement between the User and Us and is made pursuant to the terms of the Information Technology Act, 2000.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>SECTION 1 - Services</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<div style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>
    <ol style="margin-bottom:0cm;list-style-type: decimal;">
        <li style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>Fashion Trades & Agencies Private Limited is currently only responsible for collecting the EMI from the customer , an individual, resident of India (also referred to as &quot;Borrower&quot; which expression shall, unless repugnant to the context or meaning thereof include its successors and assigns) who had taken unsecured personal loan from us i.e Fashion Trades & Agencies Private Limited (also referred as &lsquo;Lender&rsquo; or &lsquo; FTAPL&rsquo;) ,through the &nbsp;mobile app of (new app) ( also referred as &quot; Fashion Trades & Agencies Private Limited)</li>
    </ol>
</div>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>1.2&nbsp;CurrentlyFashion Trades & Agencies Private Limited is no longer our service provider. We also do not have any association with any mobile app or and digital platform</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>1.3 FTAPL website, enables customer who seek to pay their outstanding EMI (&ldquo;Beneficiaries&rdquo;) of the loan taken from lender (&ldquo;Benefactor&rdquo; or &ldquo; Fashion Trades & Agencies Private Limited&rdquo;)&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>1.4 By using the Website, or the Services, You hereby acknowledge that Fashion Trades & Agencies Private Limited &nbsp;is a &ldquo; Lender&rdquo; . By using this website , it facilitates the transaction between Lender and Borrower.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;<strong>Do Not Disturb</strong></p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>In the event you have registered your phone number on the &lsquo;Do Not Disturb&rsquo; registers with your network provider, you shall ensure to take all steps to enable the Company&rsquo;s representative&rsquo;s to contact you via phone to repay the outstanding EMI and You shall ensure that such calls received by You are pursuant to You providing Us with information and You shall not register a compliant with the relevant authorities for the same.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>SECTION 2 - User(S) Eligibility</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>User(s) means an individual who uses and has the right to use the Services provided by FTAPL. Our Services are available only to borrowers who has already taken unsecured personal loan from us. Therefore, a User must not be a minor, of unsound mind or insolvent, as per Indian Law; i.e. User(s) must be at least 18 years of age to be eligible to use our Services.&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>FTAPL hereby advises You that while accessing the Website, You must follow/abide all applicable laws. FTAPL is not responsible for the consequences of Your behaviour or negligence, misfeasance or malfeasance during use of the Website / CC / Services. FTAPL at all times reserves the right to deny Services to You without any obligation to state the reasons for such withholding or withdrawal of Services.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>SECTION 3 -&nbsp;GENERAL CONDITIONS</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'><br></p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>We reserve the right to refuse service to anyone for any reason at any time.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>You understand that your content (not including credit card information), may be transferred unencrypted and involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices. Credit card information is always encrypted during transfer over networks.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>You agree not to reproduce, duplicate, copy, sell, resell or exploit any portion of the Service, use of the Service, or access to the Service or any contact on the website through which the service is provided, without express written permission by us.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>The headings used in this agreement are included for convenience only and will not limit or otherwise affect these Terms.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>SECTION 3 - ACCEPTANCE OF TERMS AND CONDITIONS</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>As a User of this&nbsp;website, You have agreed to the Terms &amp; Conditions provided hereunder or anywhere else on this Platform including but not limited to disclaimers on this Platform.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>We reserve the right, at its sole discretion, to change, modify, add or remove portions of these Terms &amp; Conditions, at any time without any prior written notice to the User. It is the User&rsquo;s responsibility to review these Terms &amp; Conditions periodically for any updates/ changes. User&rsquo;s continued use of the &nbsp;Website following the modification of these Terms and Conditions will imply the acceptance by the User of the revisions.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>SECTION 4 - YOUR ACCOUNT</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>If You wish to use the website, to pay your EMI you need to authenticate your credentials via secured mechanism i.e OTP sent to your email or phone number as per your discretion.We collect the personal information you give us such as your email address or phone number . This data is needed for the registration process to have access to your Loan Details. The user is authenticated from your existing user account.&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>You are responsible for maintaining the confidentiality and security of Your account, password/OTP, activities that occur in or through Your account and for restricting access to Your computer/mobile to prevent unauthorized access to Your account. You agree to accept responsibility for all activities that occur under Your account or password/OTP. You should take all necessary steps to ensure that the password/OTP is kept confidential and secure and should inform us immediately if You have any reason to believe that Your password/OTP has become known to anyone else, or if the password/OTP is being, or is likely to be, used in an unauthorized manner. Please ensure that the details You provide Us with are true, correct, accurate and complete</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>SECTION 5 - PRIVACY</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>FTAPL collects certain information from You in order to provide the Services. FTAPL&rsquo;s use of Your personal information is governed in accordance with the Privacy Policy located at <strong><a href="https://www.loanfront.in/privacy-policy.html"><span style="color:windowtext;text-decoration:none;">https://FTAPL.in</span><span style="color:windowtext;text-decoration:none;">&ensp;</span></a></strong>.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>SECTION 6 - LICENSE AND ACCESS</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>FTAPL grants you a limited, non-transferable and revocable license to access and use the website or any part thereof for availing the Services, but not to download any material from it (other than page caching) or modify it, or any portion of it, except with express consent of FTAPL and / or its affiliates, as may be applicable. Any unauthorized access to the Platform (or any part thereof) or any networks, servers or computer systems connected to Platform and any attempt to modify, adapt, translate or reverse engineer any part of the Platform or re-format or frame any portion of the pages of the Platform, save to the extent expressly permitted by these Terms &amp; Conditions, is not permitted.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>This license is non-transferable and does not permit any resale or commercial use of this Platform or its contents; any downloading or copying of account information for the benefit of anyone other than Your use; or any use of data mining, robots, or similar data gathering and extraction tools. The Platform or any portion of the Platform (including but not limited to any copyrighted material, trademarks, or other proprietary information) may not be reproduced, duplicated, copied, sold, resold, visited, distributed or otherwise exploited for any commercial purpose without express written consent of&nbsp;Fashion Trades & Agencies Private Limited&nbsp;and / or its affiliates, as may be applicable. Any unauthorized use of the Platform shall terminate the permission or revoke the license granted by&nbsp;Fashion Trades & Agencies Private Limited.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>SECTION 7 - MONITORING OF THE PLATFORM AND YOUR ACCOUNT</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>Fashion Trades & Agencies Private Limited always has the right and liberty to monitor the content of the website or any part thereof which shall include information provided in Your account. The monitoring of the website is important to determine the veracity of the information provided by You and that every User remains in consonance with the Terms &amp; Conditions provided herein. Subject to the Terms &amp; Conditions mentioned herein, Fashion Trades & Agencies Private Limited shall also have the liberty to remove any objectionable content which is in contravention of the Terms &amp; Conditions or any applicable laws in force in India or share such information with any governmental authority as per procedures laid down by the law for the time being in force in India.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>SECTION 8 - THIRD-PARTY LINKS</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>Certain content, products and services available via our Service may include&nbsp;service&nbsp;from third-parties.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>Third-party links on this site may direct you to third-party websites that are not affiliated with us. We are not responsible for examining or evaluating the content or accuracy and we do not warrant and will not have any liability or responsibility for any third-party materials or websites, or for any other materials, products, or services of third-parties.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>We are not liable for any harm or damages related to the purchase or use of goods, services, resources, content, or any other transactions made in connection with any third-party websites. Please review carefully the third-party&apos;s policies and practices and make sure you understand them before you engage in any transaction. Complaints, claims, concerns, or questions regarding third-party products should be directed to the third-party.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>SECTION 9 - SERVICE SUSPENSION</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>Fashion Trades & Agencies Private Limited may wish to stop providing the Services and may terminate use of it at any time without giving notice of termination to You. Unless Fashion Trades & Agencies Private Limited informs the User otherwise, upon any termination, (a) the rights and licenses granted to You in these Terms and Conditions will end and (b) User must stop using the Platform or any part thereof forthwith. Fashion Trades & Agencies Private Limited reserves the right to suspend or cease providing any Service and shall have no liability or responsibility to the User in any manner whatsoever.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>SECTION 10 - PERSONAL INFORMATION</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>Your submission of personal information through the website is governed by our Privacy Policy.&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>SECTION 11 - PROHIBITED USES</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>In addition to other prohibitions as set forth in the Terms &amp; Conditions, You are prohibited from using the Platform: (a) for any unlawful purpose; (b) to solicit others to perform or participate in any unlawful acts; (c) to violate any international, federal, provincial or state regulations, rules, laws, or local ordinances; (d) to infringe upon or violate our intellectual property rights or the intellectual property rights of others; (e) to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability; (f) to submit false or misleading information; (g) to upload or transmit viruses or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Service or of any related website, other websites, or the Internet; (h) to collect or track the personal information of others; (i) to spam, phish, pharm, pretext, spider, crawl, or scrape; (j) for any obscene or immoral purpose; or (k) to interfere with or circumvent the security features of the Service or any related website, other websites, or the Internet. We reserve the right to terminate Your use of the Service or any related website for violating any of the prohibited uses.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>SECTION 13 - DISCLAIMER OF WARRANTIES; LIMITATION OF LIABILITY</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>Notwithstanding anything to the contrary contained herein, neither Fashion Trades & Agencies Private Limited nor its affiliated companies, subsidiaries, officers, directors, employees, partners or any related party shall have any liability to You or to any third party for any indirect, incidental, special or consequential damages or any loss of revenue or profits arising under or relating to these Terms &amp; Conditions. To the maximum extent permitted by law, You waive, release, discharge and hold harmless&nbsp;Fashion Trades & Agencies Private Limited, its affiliated and subsidiary companies, and each of their directors, officers, employees, partners, and agents, from any and all claims, losses, damages, liabilities, expenses and causes of action arising out of Your use of the Platform / Website .</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>As a User, You also acknowledge that Fashion Trades & Agencies Private Limited has maintained and carried out all possible checks and balances to assure the credibility of the Users as listed on the website. The information provided on the Website &nbsp;is based on the information that is provided to Fashion Trades & Agencies Private Limited by its Users. In case the User does not disclose any information to Fashion Trades & Agencies Private Limited, and the same is not found out at the first instance by Fashion Trades & Agencies Private Limited, Fashion Trades & Agencies Private Limited shall not be responsible for any claims or liabilities.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>Fashion Trades & Agencies Private Limited shall have the exclusive right to initiate proceedings against the defaulter borrower. Fashion Trades & Agencies Private Limited shall to the best of its abilities aid the concerned User in terms of provision of information to initiate any legal proceedings. However, Fashion Trades & Agencies Private Limited shall not be responsible for any default on behalf of the User.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>We do not guarantee, represent or warrant that your use of our service will be uninterrupted, timely, secure or error-free.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>We do not warrant that the results that may be obtained from the use of the service will be accurate or reliable.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>You agree that from time to time we may remove the service for indefinite periods of time or cancel the service at any time, without notice to you.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>You expressly agree that your use of, or inability to use, the service is at your sole risk.&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>SECTION 14 - INDEMNIFICATION</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>You agree to indemnify, save, and hold Fashion Trades & Agencies Private Limited, its affiliates, contractors, employees, officers, directors, agents and its third party associates, licensors, and partners harmless from any and all claims, demands, losses, damages, and liabilities, costs and expenses, including without limitation legal fees and expenses, arising out of or related to Your use or misuse of the Services or of the Website&nbsp;.&nbsp;Any violation by You of these Terms &amp; Conditions, or any breach of the representations, warranties, and covenants made by You herein or Your infringement of any intellectual property or other right of any person or entity, or as a result of any threatening, libelous, obscene, harassing or offensive material posted/ transmitted by You on the Website reserves the right, at Your expense, to assume the exclusive defense and control of any matter for which You are required to indemnify Fashion Trades & Agencies Private Limited, including rights to settle, and You agree to cooperate with Fashion Trades & Agencies Private Limited&rsquo; defense and settlement of these claims. Fashion Trades & Agencies Private Limited will use reasonable efforts to notify you of any claim, action, or proceeding brought by a third party that is subject to the foregoing indemnification upon becoming aware of it. This paragraph shall survive termination of this Terms &amp; Conditions.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'><br></p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>SECTION 15 - Usage Conditions</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>You are advised to provide accurate information to Fashion Trades & Agencies Private Limited.Fashion Trades & Agencies Private Limited can verify the information that You have provided and choose to refuse Services or use of the Website without providing any reasons therefor.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>By using the Application or Website You agree that:</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>You have understood these Terms with Fashion Trades & Agencies Private Limited and You have clearly understood the terms and conditions of the Services.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>You shall use the Application for personal purposes only.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>You shall not assign or otherwise transfer Your account to any other person or legal entity. You shall not use the Services for unlawful purposes, including but not limited to sending or storing any unlawful material or for fraudulent purposes.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>You shall not use the Services to cause nuisance, annoyance or inconvenience.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>You shall not impair the proper operation of the network, hack or illegally access any user data from the Website or make any material change in the Website without the prior permission of Fashion Trades & Agencies Private Limited since any of these above acts will be construed as hacking or data theft under extant Indian laws</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>You shall not try to disrupt the provision of the Services to any User in any way whatsoever.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>You shall not copy, or distribute the Application or other Fashion Trades & Agencies Private Limited content without written permission from Fashion Trades & Agencies Private Limited.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>You shall keep Your account password information, or any other identification we provide You which allows access to the Services, confidential.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>You shall provide us any proof of identity we may request, and as may be specified by the Reserve Bank of India (&ldquo;RBI&rdquo;) in relation to any Customer Due Diligence or Know-Your-Customer processes, as may be applicable.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>You shall comply with all applicable law of Your city, state and the country while using the Wesbite, or the Services.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>In addition to its other rights under these Terms, Fashion Trades & Agencies Private Limited reserves the right to immediately terminate the Services, if You does not comply with any of the above.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'><br></p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>SECTION 15 : Trademark</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>All related icons and logos are registered trademarks or trademarks or service marks of Fashion Trades & Agencies Private Limited in various jurisdictions and are protected under applicable copyright, trademark and other proprietary rights laws. The unauthorized copying, modification, use or publication of these marks is strictly prohibited.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>SECTION 16 -&nbsp;Copyright</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'><br></p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>All Content on the Website/application&nbsp;is the copyright of&nbsp;Fashion Trades & Agencies Private Limited&nbsp;except any third party content and links to third party websites on our Website.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>Any systematic retrieval of&nbsp;Fashion Trades & Agencies Private Limited&nbsp;Content to create or compile, directly or indirectly, a collection, compilation, database or directory (whether through robots, spiders, automatic devices or manual processes) without written permission from&nbsp;Fashion Trades & Agencies Private Limited&nbsp;is prohibited.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>In addition, use of the Content for any purpose not expressly permitted in these Terms is prohibited and may invite legal action. As a condition of Your access to and use of&nbsp;Fashion Trades & Agencies Private Limited&nbsp;Services, You agree that You will not use the Website Services to infringe the intellectual property rights of others in any way.&nbsp;Fashion Trades & Agencies Private Limited&nbsp;reserves the right to terminate the account of any User(s) upon any infringement of the rights of others in conjunction with use of the&nbsp;Fashion Trades & Agencies Private Limited services, or if&nbsp;Fashion Trades & Agencies Private Limited&nbsp;believes that any User(s) conduct is harmful to the interests of&nbsp;Fashion Trades & Agencies Private Limited, its affiliates, or other Users, or for any other reason in&nbsp;Fashion Trades & Agencies Private Limited&nbsp;sole discretion, with or without cause.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'><br></p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>SECTION 17 - ADVERTISERS/ THIRD PARTY LINKS ON THE PLATFORM</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>Fashion Trades & Agencies Private Limited accepts no responsibility for advertisements contained within the website or any part thereof. Fashion Trades & Agencies Private Limited has no control over and accepts no responsibility for the content of any website to which a link from the Platform or any part thereof exists. Such linked websites and or mobile applications are provided &ldquo;as is&rdquo; for User&rsquo;s convenience only with no warranty, express or implied, for the information provided within them or the veracity thereof.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>SECTION 18: Consent To Electronic Communications And Transactions</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>By clicking the &ldquo;Login&rdquo;, &ldquo;Register&rdquo;, or &ldquo;I Agree&rdquo; button, You consent to conduct transactions and receive communications, notices and information from us electronically, whether sent by e-mail or other electronic means. Electronic communications shall be deemed to have been received by You when we send the electronic communication to Your email address / mobile number per our records, or when we post the electronic communication on the Website.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'><br></p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>SECTION 19 - Choice Of Law And Dispute Resolution</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>Your use of this Platform and any Term &amp; Conditions stated in this agreement is subject to laws of India. These Terms of Registration shall be governed by, and construed in accordance with, the laws of India, without reference to principles of conflicts of law. The parties agree that any and all disputes arising from or relating to these Terms of Registration, the Application or the Website shall be resolved exclusively by arbitration under the Arbitration and Concilliation Act, 1996 and the governing law of such arbitration shall be Indian Law. The arbitral tribunal shall consist of a sole arbitrator to be appointed by&nbsp;Fashion Trades & Agencies Private Limited&nbsp;and the seat and place of such arbitration shall be Kolkata.&nbsp;In case of any disputes arising out of the use of the Platform or any part thereof, Courts of&nbsp;Kolkata, India will have exclusive jurisdiction.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>SECTION 20 - CHANGES TO TERMS&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>You can review the most current version of the Terms of Service at any time at this page.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>Fashion Trades & Agencies Private Limited shall be entitled to add to, vary or amend any or all these Terms at any time and You shall be bound by such addition, variation or amendment once such addition, variation or amendment is incorporated into these Terms on the Website &nbsp; on the date that Fashion Trades & Agencies Private Limited may indicate that such addition, variation or amendment is to come into effect.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>SECTION 21 :&nbsp;REFUNDS &amp; CANCELLATION</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>Any additional payment made by you shall be refunded back within 30 days pursuant to the reconciliation of the accounts by Fashion Trades & Agencies Private Limited . Currently there is no cancellation policy as we are not disbursing any loan&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>SECTION 22 : DOCUMENT POLICY</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";text-align:justify;'>Fashion Trades & Agencies Private Limited does not return any customer documents including but not limited to IDs, Address proofs, bank statements and photographs. Fashion Trades & Agencies Private Limited may disclose the customer information documents to credit agencies bureaus, RBI or any other financial institution third party that may need the information as deemed necessary by Fashion Trades & Agencies Private Limited RBI or any other regulatory legal authority. In this regard, customer waives the privilege of privacy.</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>SECTION 23 - CONTACT INFORMATION</p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>Questions about the Terms of Service should be sent to us at <strong>SAMPARK.FTAPL@GMAIL.COM</strong></p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'><br></p>
<p style='margin:0cm;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial","sans-serif";'>&nbsp;</p>


                    
   
                  
                </div>
    
          
              
            </div>
        </div>
    </section>
    <!-- End Features Area -->

  
    <?php
    include_once('footer.php');
    ?>
